services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.4
      dockerfile: Dockerfile
    image: sail-8.4/app
    ports:
      - "80:80"  # Mapeia a porta 80 do host para 80 do container
    volumes:
      - ./:/var/www/html
    networks:
      - sail
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: shopping_list
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  sail:
    driver: bridge

volumes:
  mysql_data:
    driver: local
